[joint_1]
can_id = 0x01
master_id = 0x11
offset = 0.0
dir = -1.0
mit_pid = { kp = 200.0, kd = 6.0 }

[joint_2]
can_id = 0x02
master_id = 0x12
offset = 0.0
dir = -1.0
mit_pid = { kp = 200.0, kd = 6.0 }

[joint_3]
can_id = 0x03
master_id = 0x13
offset = 0.0
dir = -1.0
mit_pid = { kp = 200.0, kd = 6.0 }

[joint_4]
id = 4
offset = 0.0
dir = 1.0
mit_pid = { kp = 200.0, kd = 6.0 }

[joint_5]
can_id = 0x05
master_id = 0x15
offset = 0.0
dir = 1.0
mit_pid = { kp = 200.0, kd = 6.0 }